### PR TITLE
Bug fixes, updated readme file, ESC keyboard feature

### PR DESCRIPTION
**Pull request by nicholaszuccarelli**
Hi again.

This release fixes:
- https://github.com/rlemaigre/Easy-DnD/issues/90 (cannot reorder a DropList with a fixed height)

Features:
- Press ESC key to cancel the current drag event
- Prop `scrollingEdgeSize` for DropList and Drag which defines the borders for scrolling at the edge of a container (can also be disabled if `scrollingEdgeSize` = `0`)

I have also rewritten the documentation to contain all slots, props and events.

### CODE REVIEW

**Comment by rlemaigre** [comment]
Thank you for your many contributions !

This one is released on NPM as 1.16.0

**Comment by nicholaszuccarelli** [comment]
Glad to help! It’s a great package so I’m happy to contribute.

If you don’t mind me asking, would there be any chance I could have a role for managing the issues page? (There are some cases where I’d like to close issues when I provide a fix) instead of having to tag you each time :P

**Comment by nicholaszuccarelli** [comment]
Thank you! I will still get you to revise any of my pull requests.

**Comment by rlemaigre** [comment]
No problem

**Pull request merged**
