### PR TITLE
Revert change in v1.20.0 breaking draggable element interaction

### PR DESCRIPTION
**Pull request by nicholaszuccarelli**
@rlemaigre

### CODE REVIEW

**Comment by rlemaigre** [comment]
Thank you, I pushed version 1.22.0 with this.

Btw @nicholaszuccarelli it is past time you include your name as a contributor in the readme if you want to

**Comment by nicholaszuccarelli** [comment]
Do you mean as a contributor on npmjs.com?

**Comment by rlemaigre** [comment]
Yes that too, if you have an npm account I'll add you as a contributor on npm so you can publish releases without me.

But I meant in the readme on github. I think some projects have a "contributors" section at the bottom of the readme

**Comment by rlemaigre** [comment]
Oh github already shows contributors, nevermind then

image

**Comment by nicholaszuccarelli** [comment]
No worries. My NPM username is zuc0001

**Comment by rlemaigre** [comment]
Ok I added you as a maintainer on NPM, you should be able to push stuff if you "npm publish" from the lib folder.

**Comment by nicholaszuccarelli** [comment]
Awesome thanks! :)

**Pull request merged**
